version: '3'
services:
  ducktown-web:
    image: nginx
    ports:
      - "8000:80"
    volumes:
      - ./public:/usr/share/nginx/html:ro
      - ./ducktown.conf:/etc/nginx/conf.d/default.conf
    restart: always